server:
  port: ${PORT:8080}
  servlet:
    context-path: /rest/v1.0/ucation
spring:
  config:
    import: optional:dotenv:../../.env
  dotenv:
    enabled: true
  application:
    name: ucation
    version: 1.0.0
    java: 21
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CORREO_NOTIFICACIONES}
    password: ${CONTRASENA_CORREO_NOTI}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO

key:
  secret: ${SECRET_KEY}

tiempo:
  recuperarContrasena: ${TIEMPO_RECUPÉRAR_CONTRA_MIN}

jwt:
  secret: ${SECRET_JWT}
  expiracion: ${TIEMPO_EXPIRACION_JWT}

urlexcluirfilter: /rest/v1.0/ucation/login,/rest/v1.0/ucation/usuario/registrar,/rest/v1.0/ucation/recuperar-contrasena/**,/rest/v1.0/ucation/api/hello
